version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  clip:
    build: ./clip-api
    ports:
      - "8000:8000"

  uploader:
    build: ./uploader
    depends_on:
      - elasticsearch
      - clip
    environment:
      - ELASTIC_HOST=http://elasticsearch:9200
      - CLIP_HOST=http://clip:8000

  pipeline:
    build: ./pipeline
    depends_on:
      - elasticsearch
      - clip
    environment:
      - ELASTIC_HOST=http://elasticsearch:9200
      - CLIP_HOST=http://clip:8000
      - OLLAMA_HOST=http://host.docker.internal:11434/v1

volumes:
  esdata:
